"use client";
import { useState, type FormEvent } from "react";
type Place={id:number;city:"Makkah"|"Madinah";ar:string;en:string;type:string;pos:[number,number];arText:string;enText:string};
const places:Place[]=[
 {id:1,city:"Makkah",ar:"غار حراء",en:"Cave of Hira",type:"Revelation",pos:[61,29],arText:"الموضع الذي بدأ فيه نزول الوحي على النبي محمد ﷺ.",enText:"The mountain cave traditionally associated with the beginning of the first revelation."},
 {id:2,city:"Makkah",ar:"الكعبة المشرفة",en:"The Kaaba",type:"Sanctuary",pos:[48,52],arText:"قلب المسجد الحرام وأقدس موضع في الإسلام.",enText:"The heart of al-Masjid al-Haram and Islam’s holiest sanctuary."},
 {id:3,city:"Makkah",ar:"جبل ثور",en:"Jabal Thawr",type:"Hijrah",pos:[31,72],arText:"جبل ارتبط ببداية رحلة الهجرة المباركة.",enText:"A mountain associated with the opening chapter of the Hijrah journey."},
 {id:4,city:"Madinah",ar:"مسجد قباء",en:"Quba Mosque",type:"Mosque",pos:[35,63],arText:"أول مسجد أُسس على التقوى.",enText:"The first mosque established upon piety."},
 {id:5,city:"Madinah",ar:"المسجد النبوي",en:"The Prophet’s Mosque",type:"Mosque",pos:[53,46],arText:"المسجد الذي بناه النبي ﷺ وكان مركزاً للمجتمع في المدينة.",enText:"The mosque built by the Prophet ﷺ and a centre of the Madinan community."},
 {id:6,city:"Madinah",ar:"جبل أحد",en:"Mount Uhud",type:"Battle",pos:[69,22],arText:"موضع غزوة أُحد ودروسها الخالدة.",enText:"The site of the Battle of Uhud and its enduring lessons."}
];
export default function Home(){const[ar,setAr]=useState(false),[city,setCity]=useState<"Makkah"|"Madinah">("Makkah"),[selected,setSelected]=useState(places[1]),[saved,setSaved]=useState<number[]>([]),[admin,setAdmin]=useState(false),[notice,setNotice]=useState("");const q=(a:string,b:string)=>ar?a:b;const setPlace=(c:"Makkah"|"Madinah")=>{setCity(c);setSelected(places.find(p=>p.city===c)!)};const submit=(e:FormEvent)=>{e.preventDefault();setNotice(q("تم حفظ الموقع كمسودة.","Location saved as a draft."))};return <main dir={ar?"rtl":"ltr"} className={ar?"arabic":""}>
<header><a className="brand"><b>✦</b><span>Paths of<br/><i>Revelation</i></span></a><nav><a href="#map">{q("استكشف","Explore")}</a><a href="#journeys">{q("الرحلات","Journeys")}</a><a href="#about">{q("عن المنصة","About")}</a></nav><div className="actions"><button onClick={()=>setAr(!ar)}>{ar?"EN":"ع"}</button><button className="dark">{q("تسجيل الدخول","Sign in")}</button></div></header>
<section className="hero"><p className="eyebrow">{q("سِيرَةٌ · أَمَاكِنُ · ذِكْرَى","SEERAH · PLACES · MEMORY")}</p><h1>{q("اكتشف الأماكن", "Walk the places")}<br/><i>{q("التي صنعت التاريخ","where history unfolded")}</i></h1><p>{q("خريطة تفاعلية للمواقع المقدسة والتاريخية في مكة المكرمة والمدينة المنورة.","An interactive atlas of the sacred and historic places of Makkah and Madinah.")}</p><div className="tabs"><button className={city==="Makkah"?"on":""} onClick={()=>setPlace("Makkah")}>مكة <small>Makkah</small></button><button className={city==="Madinah"?"on":""} onClick={()=>setPlace("Madinah")}>المدينة <small>Madinah</small></button></div></section>
<section className="atlas" id="map"><div className="map"><div className="map-title"><small>{q("الخريطة التفاعلية","INTERACTIVE MAP")}</small><strong>{city==="Makkah"?"مكة المكرمة":"المدينة المنورة"}</strong></div><div className="grid"/><i className="road r1"/><i className="road r2"/><i className="road r3"/>{places.filter(p=>p.city===city).map(p=><button className={selected.id===p.id?"pin chosen":"pin"} style={{left:p.pos[0]+"%",top:p.pos[1]+"%"}} onClick={()=>setSelected(p)} key={p.id}>✦</button>)}<div className="zoom"><button>+</button><button>−</button></div><small className="credit">© OpenStreetMap contributors · MapLibre-ready</small></div><aside><div className="image"><div/><span>{city==="Makkah"?"مكة":"المدينة"}</span></div><article><small>{selected.type.toUpperCase()} · SACRED HISTORY</small><h2>{q(selected.ar,selected.en)}</h2><p>{q(selected.arText,selected.enText)}</p><footer><button className="story">{q("اقرأ القصة","Read the story")} ↗</button><button className={saved.includes(selected.id)?"heart active":"heart"} onClick={()=>setSaved(saved.includes(selected.id)?saved.filter(x=>x!==selected.id):[...saved,selected.id])}>{saved.includes(selected.id)?"♥":"♡"} {q("حفظ","Save")}</button></footer></article></aside></section>
<section id="journeys" className="journeys"><div><p className="eyebrow">{q("خطط رحلتك","PLAN YOUR JOURNEY")}</p><h2>{q("أماكن محفوظة لزيارتك","Your saved places, ready for a journey")}</h2></div><div><b>{String(saved.length).padStart(2,"0")}</b><span>{q("أماكن محفوظة","saved places")}</span><button>{q("إنشاء خطة","Create a plan")}</button></div></section><section id="about" className="about"><div><p className="eyebrow">{q("مُوثَّق بعناية","CAREFULLY CURATED")}</p><h2>{q("تاريخ يُستكشف باحترام","History to explore with reverence")}</h2></div><p>{q("لكل موضع مساحة لسياقه ومصادره وصوره—تجربة هادئة للاستعداد للزيارة.","Every place has room for context, sources, and imagery—a calm experience for thoughtful preparation.")}</p></section><footer className="site-footer"><span>Paths of Revelation · © 2026</span><button onClick={()=>setAdmin(true)}>Owner admin ↗</button></footer>
{admin&&<div className="modal"><form onSubmit={submit}><button type="button" className="close" onClick={()=>setAdmin(false)}>×</button><p className="eyebrow">OWNER ADMIN</p><h2>{q("إضافة موقع جديد","Add a sacred place")}</h2><label>City<select><option>Makkah</option><option>Madinah</option></select></label><div className="pair"><label>Latitude<input required placeholder="21.4225"/></label><label>Longitude<input required placeholder="39.8262"/></label></div><label>Arabic title<input required dir="rtl" placeholder="العنوان بالعربية"/></label><label>English title<input required placeholder="English title"/></label><label>Arabic description<textarea required dir="rtl"/></label><label>English description<textarea required/></label><label className="upload">Upload photos<input type="file" accept="image/*" multiple/></label><button className="dark">Save location</button>{notice&&<p>{notice}</p>}</form></div>}</main>}
