'use client';

import { useEffect, useRef, useState } from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';

type Place = { id: number; city: 'Makkah' | 'Madinah'; title: string; titleEn: string; type: string; typeEn: string; era: string; eraEn: string; description: string; descriptionEn: string; lat: number; lng: number; photo: string; source: string };
const places: Place[] = [
  { id: 1, city: 'Makkah', title: 'غار حراء', titleEn: 'Cave of Hira', type: 'موضع وحي', typeEn: 'Revelation site', era: 'بداية الوحي', eraEn: 'Beginning of revelation', description: 'الموضع الذي ارتبط ببداية نزول الوحي على النبي محمد ﷺ. نموذج تعريفي قابل للاستبدال بمادتكم العلمية المعتمدة.', descriptionEn: 'The site traditionally associated with the beginning of revelation to Prophet Muhammad ﷺ. This sample text can be replaced with your approved research.', lat: 21.4585, lng: 39.8579, photo: 'https://images.unsplash.com/photo-1565552645890-46e7e38a0c30?auto=format&fit=crop&w=1000&q=80', source: 'مادة تجريبية — أضف المصدر المعتمد' },
  { id: 2, city: 'Makkah', title: 'جبل النور', titleEn: 'Jabal al-Nour', type: 'معلم طبيعي', typeEn: 'Natural landmark', era: 'العهد المكي', eraEn: 'Makkah period', description: 'معلم بارز في مكة المكرمة، يشرف على المنطقة المحيطة بغار حراء.', descriptionEn: 'A prominent Makkah landmark overlooking the area surrounding the Cave of Hira.', lat: 21.4598, lng: 39.8601, photo: 'https://images.unsplash.com/photo-1585036156171-384164a8c675?auto=format&fit=crop&w=1000&q=80', source: 'مادة تجريبية — أضف المصدر المعتمد' },
  { id: 3, city: 'Madinah', title: 'مسجد قباء', titleEn: 'Quba Mosque', type: 'مسجد', typeEn: 'Mosque', era: 'الهجرة', eraEn: 'Hijrah', description: 'من المواقع المركزية في سيرة الهجرة، ويُعرض هنا كنموذج لبطاقة موقع ثنائية اللغة.', descriptionEn: 'A central location in the account of the Hijrah, presented here as a bilingual sample place card.', lat: 24.4398, lng: 39.6176, photo: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=1000&q=80', source: 'مادة تجريبية — أضف المصدر المعتمد' },
  { id: 4, city: 'Madinah', title: 'جبل أُحد', titleEn: 'Mount Uhud', type: 'موقع تاريخي', typeEn: 'Historic site', era: 'غزوة أُحد', eraEn: 'Battle of Uhud', description: 'معلم تاريخي شمال المدينة المنورة، مرتبط بأحداث غزوة أُحد.', descriptionEn: 'A historic landmark north of Madinah associated with events of the Battle of Uhud.', lat: 24.5060, lng: 39.6159, photo: 'https://images.unsplash.com/photo-1532264523420-881a47db012d?auto=format&fit=crop&w=1000&q=80', source: 'مادة تجريبية — أضف المصدر المعتمد' }
];
export default function Home() {
 const mapRef=useRef<HTMLDivElement>(null); const mapInstance=useRef<L.Map|null>(null); const [language,setLanguage]=useState<'ar'|'en'>('ar'); const [city,setCity]=useState<'all'|Place['city']>('all'); const [selected,setSelected]=useState(places[0]); const [favorites,setFavorites]=useState<number[]>([1]); const [itinerary,setItinerary]=useState(false); const [admin,setAdmin]=useState(false); const [shared,setShared]=useState(false); const ar=language==='ar'; const visible=city==='all'?places:places.filter(p=>p.city===city);
 useEffect(()=>{if(!mapRef.current||mapInstance.current)return;const map=L.map(mapRef.current,{scrollWheelZoom:true,zoomControl:true}).setView([23,39.75],6);mapInstance.current=map;L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(map);places.forEach(place=>{const marker=L.circleMarker([place.lat,place.lng],{radius:9,color:'#fff',weight:3,fillColor:'#315e4c',fillOpacity:1}).addTo(map);marker.bindTooltip(place.title,{direction:'top',offset:[0,-8],opacity:.94});marker.on('click',()=>{setSelected(place);map.flyTo([place.lat,place.lng],13,{duration:.65})})});return()=>{map.remove();mapInstance.current=null}},[]);
 const text=(p:Place,k:'title'|'type'|'era'|'description')=>ar?p[k]:p[(k+'En') as keyof Place] as string; const favorite=(id:number)=>setFavorites(x=>x.includes(id)?x.filter(i=>i!==id):[...x,id]);
 return <main dir={ar?'rtl':'ltr'} className="site"><header><a className="brand" href="#map"><span>ر</span><b>{ar?'دروب الوحي':'Paths of Revelation'}<small>{ar?'خريطة السيرة النبوية':'A map of prophetic heritage'}</small></b></a><nav><button onClick={()=>setItinerary(true)}>{ar?'رحلاتي':'My trips'} <em>{favorites.length}</em></button><button onClick={()=>setAdmin(true)}>{ar?'إدارة المحتوى':'Content admin'}</button><button onClick={()=>setLanguage(ar?'en':'ar')}>{ar?'English':'العربية'}</button><button className="solid">{ar?'تسجيل الدخول':'Sign in'}</button></nav></header>
 <section className="hero"><div><p>{ar?'مكة المكرمة · المدينة المنورة':'MAKKAH · MADINAH'}</p><h1>{ar?<>اكتشف الأماكن التي تحكي <i>السيرة</i></>:<>Discover places that tell the <i>Seerah</i></>}</h1><small>{ar?'خريطة حيّة، وقصص موثقة، وخطط زيارة تشاركها مع من تحب.':'A living map, sourced stories, and visit plans to share.'}</small></div><aside>◌ {ar?'تصفّح بأدب ومعرفة':'Explore with care and knowledge'}</aside></section>
 <section id="map" className="workspace"><aside className="explorer"><div className="explorer-heading"><div><p>{ar?'استكشف الخريطة':'EXPLORE THE MAP'}</p><h2>{ar?'الأماكن المقدسة':'Sacred places'}</h2></div><span>{visible.length}</span></div><div className="filters"><button className={city==='all'?'active':''} onClick={()=>setCity('all')}>{ar?'الكل':'All'}</button><button className={city==='Makkah'?'active':''} onClick={()=>setCity('Makkah')}>{ar?'مكة':'Makkah'}</button><button className={city==='Madinah'?'active':''} onClick={()=>setCity('Madinah')}>{ar?'المدينة':'Madinah'}</button></div><div className="place-list">{visible.map(p=><button className={selected.id===p.id?'selected':''} onClick={()=>setSelected(p)} key={p.id}><img src={p.photo} alt=""/><span><b>{text(p,'title')}</b><small>{text(p,'type')} · {text(p,'era')}</small></span><i>↗</i></button>)}</div><footer>{ar?'© OpenStreetMap · جميع المواقع مرتبطة بإحداثياتها':'© OpenStreetMap · all places use GPS coordinates'}</footer></aside><div className="map-area"><div ref={mapRef} className="map" aria-label={ar?'خريطة تفاعلية لمكة والمدينة':'Interactive map of Makkah and Madinah'}/></div><article className="card"><img src={selected.photo} alt={text(selected,'title')}/><div><p>{selected.city==='Makkah'?(ar?'مكة المكرمة':'MAKKAH'):(ar?'المدينة المنورة':'MADINAH')} · {text(selected,'type')}</p><section><h2>{text(selected,'title')}</h2><button onClick={()=>favorite(selected.id)}>{favorites.includes(selected.id)?'♥':'♡'}</button></section><p className="description">{text(selected,'description')}</p><aside><b>{ar?'المصدر':'Source'}</b><small>{selected.source}</small></aside><nav><a target="_blank" href={'https://www.openstreetmap.org/?mlat='+selected.lat+'&mlon='+selected.lng+'#map=15/'+selected.lat+'/'+selected.lng}>{ar?'الاتجاهات':'Directions'} ↗</a><button onClick={()=>setItinerary(true)}>{ar?'أضف إلى رحلة':'Add to trip'} +</button></nav></div></article></section>
 <section className="principles"><div><span>01</span><h3>{ar?'مصادر واضحة':'Clear sources'}</h3><p>{ar?'لكل موقع مساحة للمراجع والتحقق العلمي.':'Every place makes room for references and scholarly verification.'}</p></div><div><span>02</span><h3>{ar?'رحلتك الخاصة':'Your own journey'}</h3><p>{ar?'احفظ الأماكن، رتّب الأيام، وشارك خطتك.':'Save places, arrange your days, and share your plan.'}</p></div><div><span>03</span><h3>{ar?'لغتان، معنى واحد':'Two languages, one meaning'}</h3><p>{ar?'إدارة مستقلة للنص العربي وترجمته الإنجليزية.':'Independently managed Arabic and English content.'}</p></div></section>
 {itinerary&&<div className="backdrop" onClick={()=>setItinerary(false)}><section className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setItinerary(false)}>×</button><p>{ar?'مخطط الرحلة':'TRIP PLANNER'}</p><h2>{ar?'عمرة وزيارة · ٣ أيام':'Umrah & Visit · 3 days'}</h2><small>{ar?'رتّب الأماكن ثم أرسل رابطاً خاصاً لأصدقائك.':'Arrange saved places, then send a private link to friends.'}</small><div className="trip-items">{places.filter(p=>favorites.includes(p.id)).map(p=><div key={p.id}><span>⠿</span><b>{text(p,'title')}</b><small>{p.city}</small></div>)}</div><button className="solid wide" onClick={()=>setShared(true)}>{shared?(ar?'تم نسخ رابط المشاركة ✓':'Share link copied ✓'):(ar?'مشاركة مع الأصدقاء':'Share with friends')}</button></section></div>}
 {admin&&<div className="backdrop" onClick={()=>setAdmin(false)}><section className="modal admin" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setAdmin(false)}>×</button><p>{ar?'لوحة الإدارة':'ADMIN PANEL'}</p><h2>{ar?'إضافة موقع جديد':'Add a new place'}</h2><small>{ar?'تُحفظ المسودة للمراجعة قبل النشر العام.':'Drafts are reviewed before public publishing.'}</small><div className="form"><label>{ar?'العنوان بالعربية':'Arabic title'}<input placeholder="مثال: مسجد..."/></label><label>{ar?'العنوان بالإنجليزية':'English title'}<input placeholder="Example: Mosque..."/></label><label>GPS<input placeholder="21.4225, 39.8262"/></label><label>{ar?'المدينة':'City'}<select><option>{ar?'مكة المكرمة':'Makkah'}</option><option>{ar?'المدينة المنورة':'Madinah'}</option></select></label><label className="full">{ar?'الوصف بالعربية':'Arabic description'}<textarea/></label><label className="full">{ar?'الوصف بالإنجليزية':'English description'}<textarea/></label></div><div className="upload">＋ {ar?'إضافة صور الموقع':'Add place photos'}</div><button className="solid wide">{ar?'حفظ كمسودة للمراجعة':'Save draft for review'}</button></section></div>}</main>;
}
